server:
  port: 80
eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:    # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #单机版
      #defaultZone: http://localhost:6001/eureka/
      #集群版
      defaultZone: http://127.0.0.1:6002/eureka/,http://127.0.0.1:6001/eureka/